#!/bin/bash

# extra credit: uazo

set -e
source vars.sh

cd $SRC_DIR
pwd

# install builds deps
# sudo build/install-build-deps-android.sh
# gclient runhooks

# generate ninja files and autogenerated files
# gn gen --args="$(cat $BASE_DIR/cromite/build/cromite.gn_args) target_cpu=\"arm64\" " out/arm64
gn gen --args="target_os = \"android\" target_cpu = \"arm64\" $(cat $BASE_DIR/cromite/build/cromite.gn_args) system_webview_package_name=\"com.android.webview\" enable_trybot_verification=false " out/arm64_webview

# build time!
# set NINJA_SUMMARIZE_BUILD=1
time autoninja -C out/arm64_webview system_webview_apk